version: 5.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - fortis-5
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
environment:
  my_secret: 
    secure: 0+VzkYXigwy3FEyJ70odmw==
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
install:
  - nuget install sitecorelicense -ExcludeVersion