---
ID: "fb5bb786-b383-4190-b69b-4cd13ff00496"
Parent: "53a47e66-b7f9-45bd-90e4-6ea9248587a8"
Template: "53a47e66-b7f9-45bd-90e4-6ea9248587a8"
Path: /sitecore/templates/Fortis/Page Types/Content Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170111T193806Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
